from tkinter import *
global scvalue
def click(event):
    text = event.widget.cget("text")
    print(text)
    if text ==  "=":
        if scvalue.get().isdigit():
            value = eval(screen.get())
        else:
            value = eval(screen.get())
            scvalue.set(value)
            screen.update()
    elif text =="c":
        scvalue.set("")
        screen.update()
    else:
        scvalue.set(scvalue.get()+text)
        screen.update()
root =Tk()
root.geometry("600x800")
root.title("calculater by shivam using Tkinter")
scvalue = StringVar()
scvalue.set("")
screen = Entry(root,textvar=scvalue,font = "lucida 40 bold")
screen.pack(fill= X,ipadx=8,pady=10, padx=10)
f = Frame(root,bg = "red")
b = Button(f,text = "9",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=15,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "8",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=15,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "7",padx = 10, pady = 5,font= "licida 35 bold")
b.pack(side=LEFT ,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()
f = Frame(root,bg = "blue")
b = Button(f,text = "6",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=15,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "5",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=15,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "4",padx = 10, pady = 5,font= "licida 35 bold")
b.pack(side=LEFT ,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()
f = Frame(root,bg = "purple")
b = Button(f,text = "3",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=15,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "2",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=15,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "1",padx = 10, pady = 5,font= "licida 35 bold")
b.pack(side=LEFT ,padx=15,pady=5)
b.bind("<Button-1>",click)
f.pack()
f = Frame(root,bg = "red")
b = Button(f,text = "0",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=17,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "+",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=16,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "-",padx = 10, pady = 5,font= "licida 35 bold")
b.pack(side=LEFT ,padx=16.5,pady=5)
b.bind("<Button-1>",click)
f.pack()
f = Frame(root,bg = "yellow")
b = Button(f,text = "*",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=16,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "/",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=15,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "%",padx = 10, pady = 5,font= "licida 35 bold")
b.pack(side=LEFT ,padx=16,pady=5)
b.bind("<Button-1>",click)
f.pack()
f = Frame(root,bg = "blue")
b = Button(f,text = ".",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=16.5,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "c",padx = 10 , pady = 5,font= "licida 35 bold")
b.pack(side=LEFT, padx=16,pady=5)
b.bind("<Button-1>",click)
b = Button(f,text = "=",padx = 10, pady = 5,font= "licida 35 bold")
b.pack(side=LEFT ,padx=16,pady=5)
b.bind("<Button-1>",click)
f.pack()
root.mainloop()